<a href="https://colab.research.google.com/github/kmayutrisna/MLCrashCourse/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy Tutorial**

# **Import** **Numpy**
Menggunkana perintah import untuk mengambil library Numpy dan np digunakan untuk mengakses NumPy agar lebih singkat

In [1]:
import numpy as np 

# **Populate arrays with specific numbers**
`np.array` digunakan untuk membuat matrix dengan menggunakan nilai yang kita pilih sendiri. Misalkan pada contoh ini kita akan menggunakan `np.array` untuk membuat 8-element vector:


In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


Kita juga dapat menggunakan `np.array` untuk membuat sebuah *two-dimensional matrix*. Untuk membuat two-dimensional matrix, dengan menambahkan tanda kurung siku. Misalkan, kita ingin membuat matrix 3x2:


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


Untuk membuat mtrix 0 dapat menggunakan perintah `np.zeros`


In [4]:
zeros_matrix = np.zeros(5)
print(zeros_matrix)

[0. 0. 0. 0. 0.]


# **Populate arrays with sequences of numbers**
Kita dapat membuat array dengan mengisinya dengan urutan angka

In [5]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


Perintah np.arrange akan menghasilkan sequence yang memasukkan juga nilai terendah tetapi tidak nilai tertingginya.

# **Populate arrays with random numbers**
Numpy menyediakan beberapa variasi fungsi untuk membuat matrix dengan random numbers terhadap range yang ditentutkan. Misalkan, `np.random.randint` menghasilkan nilai acak integer diantara nilai terendah dan tertinggi. Contoh berikut akan menghasilkan sebuah 6-element vector dengan random integer antara 50 dan 100.


In [7]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[97 86 77 73 93 60]


Perlu diingat bahwa nilai tertinggi yang dihasilkan dari perintah `np.random.randint` adalah nilai tertinggi dikurangi 1.

Untuk membuat random floating-point values atau nilai float antara 0.0 dan 1.0 menggunakan perintah `np.random.random`. Contohnya adalah:

In [8]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.32429079 0.67915603 0.09351667 0.97872519 0.5684261  0.25083649]


# **Mathematical Operations on NumPy Operands**
Jika kita ingin menambahkan atau mengurangi dua vektor atau matrik, kita memerlukan linear arlegra agar keduanya memiliki dimendi yang sama. Selanjutnya, jika kita ingin mengalikan dua vektor atau matrik, linear algebra memberlakukan aturan yang ketat untuk penyesuaian dimensi pada operasi tersebut. Beruntungnya, NumPy menggunakan trik yang disebut dengan *broadcasting* untuk melebarkan secara virtual operand yang ecil ke dimensi yang sesuai untuk linear algebra. Misalkan, contoh berikut menggunakan broadcasting untuk menambahkan 2.0 ke semua item pada vektor yang dibuat pada code cell sebelumnya: 

In [9]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.32429079 2.67915603 2.09351667 2.97872519 2.5684261  2.25083649]


Kode berikut ini menggunakan broadcasting untuk mengalikan setiap cell pada vektor dengan 3:

In [10]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[291 258 231 219 279 180]


# **Task 1: Create a Linear Dataset**
Tujuannya adalah untuk membuat dataset sederhana yang terdiri dari sebuah single feature dan sebuah label sebagai berikut:
Tetapkan urutan bilangan bulat dari 6 hingga 20 (inklusif) ke array NumPy bernama feature.
Tetapkan 15 nilai ke array NumPy bernama label sedemikian rupa sehingga:

  `label = (3)(feature) + 4`

Misalkan nilai pertama untuk label haruslah

`label = (3)(6) + 4 = 22`

In [12]:
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


# **Task 2: Add Some Noise to the Dataset**
Untuk membuat dataset lebih nyata, tambahkan random noise kedalam setiap elemen dari array label yang telah dibuat. Untuk lebih tepat, ubah setiap nilai yang ditetapkan untuk label dengan menambahkan different random floating-point value antara -2 dan +2. Jangan mengandalkan broadcasting, sebagai gantinya buat array noise yang memiliki dimensi yang sama dengan label.


In [13]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[ 0.38922045 -0.14972181  1.98877765  0.4001908  -1.87960552 -1.97720709
 -1.72295866 -1.1722819  -0.7973715  -0.86024323  1.03808722  0.42257346
  1.78359517  0.20635133  0.34258396]
[22.38922045 24.85027819 29.98877765 31.4001908  32.12039448 35.02279291
 38.27704134 41.8277181  45.2026285  48.13975677 53.03808722 55.42257346
 59.78359517 61.20635133 64.34258396]
